//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XRouteTestClient.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OPTIMIZATION {
            get {
                return ((string)(this["OPTIMIZATION"]));
            }
            set {
                this["OPTIMIZATION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SPEED_PROFILE {
            get {
                return ((string)(this["SPEED_PROFILE"]));
            }
            set {
                this["SPEED_PROFILE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AVOID_TOLLROADS {
            get {
                return ((string)(this["AVOID_TOLLROADS"]));
            }
            set {
                this["AVOID_TOLLROADS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AVOID_VIGNETTEROADS {
            get {
                return ((string)(this["AVOID_VIGNETTEROADS"]));
            }
            set {
                this["AVOID_VIGNETTEROADS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AVOID_HIGHWAYS {
            get {
                return ((string)(this["AVOID_HIGHWAYS"]));
            }
            set {
                this["AVOID_HIGHWAYS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AVOID_FERRIES {
            get {
                return ((string)(this["AVOID_FERRIES"]));
            }
            set {
                this["AVOID_FERRIES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AVOID_RESIDENTS_ONLY {
            get {
                return ((string)(this["AVOID_RESIDENTS_ONLY"]));
            }
            set {
                this["AVOID_RESIDENTS_ONLY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AVOID_URBAN_AREAS {
            get {
                return ((string)(this["AVOID_URBAN_AREAS"]));
            }
            set {
                this["AVOID_URBAN_AREAS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AVOID_RAMPS {
            get {
                return ((string)(this["AVOID_RAMPS"]));
            }
            set {
                this["AVOID_RAMPS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EXCLUDE_COUNTRIES {
            get {
                return ((string)(this["EXCLUDE_COUNTRIES"]));
            }
            set {
                this["EXCLUDE_COUNTRIES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ROUTING_COUNTRIES {
            get {
                return ((string)(this["ROUTING_COUNTRIES"]));
            }
            set {
                this["ROUTING_COUNTRIES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.16")]
        public string REQUEST_VERSION {
            get {
                return ((string)(this["REQUEST_VERSION"]));
            }
            set {
                this["REQUEST_VERSION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string COUNTRY_ENCODING {
            get {
                return ((string)(this["COUNTRY_ENCODING"]));
            }
            set {
                this["COUNTRY_ENCODING"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("truckfast")]
        public string ProfileRoute {
            get {
                return ((string)(this["ProfileRoute"]));
            }
            set {
                this["ProfileRoute"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7501785")]
        public double y2 {
            get {
                return ((double)(this["y2"]));
            }
            set {
                this["y2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4182599")]
        public double x2 {
            get {
                return ((double)(this["x2"]));
            }
            set {
                this["x2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4677217")]
        public double y1 {
            get {
                return ((double)(this["y1"]));
            }
            set {
                this["y1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1017459")]
        public double x1 {
            get {
                return ((double)(this["x1"]));
            }
            set {
                this["x1"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int scroll {
            get {
                return ((int)(this["scroll"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://127.0.0.1:50030/xroute/ws/XRoute")]
        public string UrlRoute {
            get {
                return ((string)(this["UrlRoute"]));
            }
            set {
                this["UrlRoute"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://127.0.0.1:50010/xmap/ws/XMap")]
        public string UrlMap {
            get {
                return ((string)(this["UrlMap"]));
            }
            set {
                this["UrlMap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AUTO_LINKING")]
        public string LinkType_START {
            get {
                return ((string)(this["LinkType_START"]));
            }
            set {
                this["LinkType_START"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AUTO_LINKING")]
        public string LinkType_DESTINATION {
            get {
                return ((string)(this["LinkType_DESTINATION"]));
            }
            set {
                this["LinkType_DESTINATION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PTV_MERCATOR")]
        public string COORDFORMAT {
            get {
                return ((string)(this["COORDFORMAT"]));
            }
            set {
                this["COORDFORMAT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string START_TIME {
            get {
                return ((string)(this["START_TIME"]));
            }
            set {
                this["START_TIME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IS_DESTTIME {
            get {
                return ((string)(this["IS_DESTTIME"]));
            }
            set {
                this["IS_DESTTIME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DYNAMIC_PROFILE {
            get {
                return ((string)(this["DYNAMIC_PROFILE"]));
            }
            set {
                this["DYNAMIC_PROFILE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ENABLE_DYNAMIC {
            get {
                return ((string)(this["ENABLE_DYNAMIC"]));
            }
            set {
                this["ENABLE_DYNAMIC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ROADEDITOR_ATTRIBUTESET {
            get {
                return ((string)(this["ROADEDITOR_ATTRIBUTESET"]));
            }
            set {
                this["ROADEDITOR_ATTRIBUTESET"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("STANDARD")]
        public string DetailLevel {
            get {
                return ((string)(this["DetailLevel"]));
            }
            set {
                this["DetailLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableTurningList {
            get {
                return ((bool)(this["EnableTurningList"]));
            }
            set {
                this["EnableTurningList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LOW_EMISSION_ZONE_TYPE {
            get {
                return ((string)(this["LOW_EMISSION_ZONE_TYPE"]));
            }
            set {
                this["LOW_EMISSION_ZONE_TYPE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ROUTE_LANGUAGE {
            get {
                return ((string)(this["ROUTE_LANGUAGE"]));
            }
            set {
                this["ROUTE_LANGUAGE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ROADEDITOR_ADDITIONAL_OPTIONS {
            get {
                return ((string)(this["ROADEDITOR_ADDITIONAL_OPTIONS"]));
            }
            set {
                this["ROADEDITOR_ADDITIONAL_OPTIONS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string START_TIME_ROADEDITOR {
            get {
                return ((string)(this["START_TIME_ROADEDITOR"]));
            }
            set {
                this["START_TIME_ROADEDITOR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DISTANCE_MEASURE {
            get {
                return ((string)(this["DISTANCE_MEASURE"]));
            }
            set {
                this["DISTANCE_MEASURE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ROUTING_RECTANGLE {
            get {
                return ((string)(this["ROUTING_RECTANGLE"]));
            }
            set {
                this["ROUTING_RECTANGLE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ROADEDITOR_LAYERNAME {
            get {
                return ((string)(this["ROADEDITOR_LAYERNAME"]));
            }
            set {
                this["ROADEDITOR_LAYERNAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GENERATE_EXTWAYPOINTS {
            get {
                return ((string)(this["GENERATE_EXTWAYPOINTS"]));
            }
            set {
                this["GENERATE_EXTWAYPOINTS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EXPERT_OPTIONS {
            get {
                return ((string)(this["EXPERT_OPTIONS"]));
            }
            set {
                this["EXPERT_OPTIONS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ENABLE_ROADEDITOR {
            get {
                return ((string)(this["ENABLE_ROADEDITOR"]));
            }
            set {
                this["ENABLE_ROADEDITOR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string STREET {
            get {
                return ((string)(this["STREET"]));
            }
            set {
                this["STREET"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ExceptionPath_AbsMalus {
            get {
                return ((int)(this["ExceptionPath_AbsMalus"]));
            }
            set {
                this["ExceptionPath_AbsMalus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ExceptionPath_RelMalus {
            get {
                return ((int)(this["ExceptionPath_RelMalus"]));
            }
            set {
                this["ExceptionPath_RelMalus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExceptionPath_Street {
            get {
                return ((string)(this["ExceptionPath_Street"]));
            }
            set {
                this["ExceptionPath_Street"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExceptionPath_BinaryPathDescription {
            get {
                return ((string)(this["ExceptionPath_BinaryPathDescription"]));
            }
            set {
                this["ExceptionPath_BinaryPathDescription"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExceptionPath_ExtSegments {
            get {
                return ((string)(this["ExceptionPath_ExtSegments"]));
            }
            set {
                this["ExceptionPath_ExtSegments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("greenzones")]
        public string ProfileMap {
            get {
                return ((string)(this["ProfileMap"]));
            }
            set {
                this["ProfileMap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AVOID_LOW_EMISSION_ZONES {
            get {
                return ((string)(this["AVOID_LOW_EMISSION_ZONES"]));
            }
            set {
                this["AVOID_LOW_EMISSION_ZONES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DYNAMIC_TIME_ON_STATICROUTE {
            get {
                return ((string)(this["DYNAMIC_TIME_ON_STATICROUTE"]));
            }
            set {
                this["DYNAMIC_TIME_ON_STATICROUTE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int ViaRadius {
            get {
                return ((int)(this["ViaRadius"]));
            }
            set {
                this["ViaRadius"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("932930")]
        public string ViaX {
            get {
                return ((string)(this["ViaX"]));
            }
            set {
                this["ViaX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ViaY {
            get {
                return ((string)(this["ViaY"]));
            }
            set {
                this["ViaY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SegmentAttributes {
            get {
                return ((bool)(this["SegmentAttributes"]));
            }
            set {
                this["SegmentAttributes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ExtendedRoute {
            get {
                return ((bool)(this["ExtendedRoute"]));
            }
            set {
                this["ExtendedRoute"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DisplayRoadEditorLayer {
            get {
                return ((bool)(this["DisplayRoadEditorLayer"]));
            }
            set {
                this["DisplayRoadEditorLayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color BoundingRectangles_Color {
            get {
                return ((global::System.Drawing.Color)(this["BoundingRectangles_Color"]));
            }
            set {
                this["BoundingRectangles_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int BoundingRectangles_Width {
            get {
                return ((int)(this["BoundingRectangles_Width"]));
            }
            set {
                this["BoundingRectangles_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BoundingRectangles_Transparent {
            get {
                return ((bool)(this["BoundingRectangles_Transparent"]));
            }
            set {
                this["BoundingRectangles_Transparent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BoundingRectanglesC {
            get {
                return ((int)(this["BoundingRectanglesC"]));
            }
            set {
                this["BoundingRectanglesC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BoundingRectanglesOffset {
            get {
                return ((int)(this["BoundingRectanglesOffset"]));
            }
            set {
                this["BoundingRectanglesOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lime")]
        public global::System.Drawing.Color ManoeuvreGroup_Color {
            get {
                return ((global::System.Drawing.Color)(this["ManoeuvreGroup_Color"]));
            }
            set {
                this["ManoeuvreGroup_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int ManoeuvreGroup_Width {
            get {
                return ((int)(this["ManoeuvreGroup_Width"]));
            }
            set {
                this["ManoeuvreGroup_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ManoeuvreGroup_Transparent {
            get {
                return ((bool)(this["ManoeuvreGroup_Transparent"]));
            }
            set {
                this["ManoeuvreGroup_Transparent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ManoeuvreGroup_Enabled {
            get {
                return ((bool)(this["ManoeuvreGroup_Enabled"]));
            }
            set {
                this["ManoeuvreGroup_Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ManoeuvreGroup_Ratio {
            get {
                return ((string)(this["ManoeuvreGroup_Ratio"]));
            }
            set {
                this["ManoeuvreGroup_Ratio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("flaggreen.bmp")]
        public string Waypoint_START {
            get {
                return ((string)(this["Waypoint_START"]));
            }
            set {
                this["Waypoint_START"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("flagblue.bmp")]
        public string Waypoint_VIA {
            get {
                return ((string)(this["Waypoint_VIA"]));
            }
            set {
                this["Waypoint_VIA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("flagred.bmp")]
        public string Waypoint_DEST {
            get {
                return ((string)(this["Waypoint_DEST"]));
            }
            set {
                this["Waypoint_DEST"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("location.bmp")]
        public string DefaultIcon {
            get {
                return ((string)(this["DefaultIcon"]));
            }
            set {
                this["DefaultIcon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dealer.bmp")]
        public string TimeEventIcon {
            get {
                return ((string)(this["TimeEventIcon"]));
            }
            set {
                this["TimeEventIcon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Magenta")]
        public global::System.Drawing.Color SegmentWithTruckToll_Color {
            get {
                return ((global::System.Drawing.Color)(this["SegmentWithTruckToll_Color"]));
            }
            set {
                this["SegmentWithTruckToll_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Green")]
        public global::System.Drawing.Color SegmentWithoutTruckToll_Color {
            get {
                return ((global::System.Drawing.Color)(this["SegmentWithoutTruckToll_Color"]));
            }
            set {
                this["SegmentWithoutTruckToll_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-8")]
        public int SegmentToll_Width {
            get {
                return ((int)(this["SegmentToll_Width"]));
            }
            set {
                this["SegmentToll_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color Route_Color {
            get {
                return ((global::System.Drawing.Color)(this["Route_Color"]));
            }
            set {
                this["Route_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-5")]
        public int Route_Width {
            get {
                return ((int)(this["Route_Width"]));
            }
            set {
                this["Route_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int Priority_Route {
            get {
                return ((int)(this["Priority_Route"]));
            }
            set {
                this["Priority_Route"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1100")]
        public int Priority_Toll {
            get {
                return ((int)(this["Priority_Toll"]));
            }
            set {
                this["Priority_Toll"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1002")]
        public int Priority_BoundingRect {
            get {
                return ((int)(this["Priority_BoundingRect"]));
            }
            set {
                this["Priority_BoundingRect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1003")]
        public int Priority_ManoeuvreGroups {
            get {
                return ((int)(this["Priority_ManoeuvreGroups"]));
            }
            set {
                this["Priority_ManoeuvreGroups"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1004")]
        public int Priority_Manoeuvres {
            get {
                return ((int)(this["Priority_Manoeuvres"]));
            }
            set {
                this["Priority_Manoeuvres"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1005")]
        public int Priority_Waypoints {
            get {
                return ((int)(this["Priority_Waypoints"]));
            }
            set {
                this["Priority_Waypoints"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1006")]
        public int Priority_Timeevents {
            get {
                return ((int)(this["Priority_Timeevents"]));
            }
            set {
                this["Priority_Timeevents"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Visibility_Route {
            get {
                return ((bool)(this["Visibility_Route"]));
            }
            set {
                this["Visibility_Route"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool Visibility_Toll {
            get {
                return ((bool)(this["Visibility_Toll"]));
            }
            set {
                this["Visibility_Toll"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool Visibility_BoundingRect {
            get {
                return ((bool)(this["Visibility_BoundingRect"]));
            }
            set {
                this["Visibility_BoundingRect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool Visibility_ManoeuvreGroups {
            get {
                return ((bool)(this["Visibility_ManoeuvreGroups"]));
            }
            set {
                this["Visibility_ManoeuvreGroups"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool Visibility_Manoeuvres {
            get {
                return ((bool)(this["Visibility_Manoeuvres"]));
            }
            set {
                this["Visibility_Manoeuvres"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Visibility_Waypoints {
            get {
                return ((bool)(this["Visibility_Waypoints"]));
            }
            set {
                this["Visibility_Waypoints"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool Visibility_Timeevents {
            get {
                return ((bool)(this["Visibility_Timeevents"]));
            }
            set {
                this["Visibility_Timeevents"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Form_RouteListSegment {
            get {
                return ((bool)(this["Form_RouteListSegment"]));
            }
            set {
                this["Form_RouteListSegment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Visibility_Ferries {
            get {
                return ((bool)(this["Visibility_Ferries"]));
            }
            set {
                this["Visibility_Ferries"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cyan")]
        public global::System.Drawing.Color Color_Ferries {
            get {
                return ((global::System.Drawing.Color)(this["Color_Ferries"]));
            }
            set {
                this["Color_Ferries"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-10")]
        public int Width_Ferries {
            get {
                return ((int)(this["Width_Ferries"]));
            }
            set {
                this["Width_Ferries"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1007")]
        public int Priority_Ferries {
            get {
                return ((int)(this["Priority_Ferries"]));
            }
            set {
                this["Priority_Ferries"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool cbxURL_Map {
            get {
                return ((bool)(this["cbxURL_Map"]));
            }
            set {
                this["cbxURL_Map"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("location_rough.bmp")]
        public string Waypoint_FUZZY {
            get {
                return ((string)(this["Waypoint_FUZZY"]));
            }
            set {
                this["Waypoint_FUZZY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool texts {
            get {
                return ((bool)(this["texts"]));
            }
            set {
                this["texts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Transparency_Toll {
            get {
                return ((bool)(this["Transparency_Toll"]));
            }
            set {
                this["Transparency_Toll"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1007")]
        public int Priority_RoutePoint {
            get {
                return ((int)(this["Priority_RoutePoint"]));
            }
            set {
                this["Priority_RoutePoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Visibility_Routepoint {
            get {
                return ((bool)(this["Visibility_Routepoint"]));
            }
            set {
                this["Visibility_Routepoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("location.bmp")]
        public string Icon_Routepoint {
            get {
                return ((string)(this["Icon_Routepoint"]));
            }
            set {
                this["Icon_Routepoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowScale {
            get {
                return ((bool)(this["ShowScale"]));
            }
            set {
                this["ShowScale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RETOUR {
            get {
                return ((bool)(this["RETOUR"]));
            }
            set {
                this["RETOUR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string vp_TYPE {
            get {
                return ((string)(this["vp_TYPE"]));
            }
            set {
                this["vp_TYPE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string vp_TOTAL_WEIGHT {
            get {
                return ((string)(this["vp_TOTAL_WEIGHT"]));
            }
            set {
                this["vp_TOTAL_WEIGHT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string vp_TRAILER_WEIGHT {
            get {
                return ((string)(this["vp_TRAILER_WEIGHT"]));
            }
            set {
                this["vp_TRAILER_WEIGHT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string vp_AXLE_WEIGTH {
            get {
                return ((string)(this["vp_AXLE_WEIGTH"]));
            }
            set {
                this["vp_AXLE_WEIGTH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string vp_NUMBER_OF_AXLES {
            get {
                return ((string)(this["vp_NUMBER_OF_AXLES"]));
            }
            set {
                this["vp_NUMBER_OF_AXLES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string vp_EMISSION_CLASS {
            get {
                return ((string)(this["vp_EMISSION_CLASS"]));
            }
            set {
                this["vp_EMISSION_CLASS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string vp_HEIGHT {
            get {
                return ((string)(this["vp_HEIGHT"]));
            }
            set {
                this["vp_HEIGHT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string vp_LENGTH {
            get {
                return ((string)(this["vp_LENGTH"]));
            }
            set {
                this["vp_LENGTH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string vp_WIDTH {
            get {
                return ((string)(this["vp_WIDTH"]));
            }
            set {
                this["vp_WIDTH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string vp_CYLINDER_CAPACITY {
            get {
                return ((string)(this["vp_CYLINDER_CAPACITY"]));
            }
            set {
                this["vp_CYLINDER_CAPACITY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string vp_NUMBER_OF_PASSENGERS {
            get {
                return ((string)(this["vp_NUMBER_OF_PASSENGERS"]));
            }
            set {
                this["vp_NUMBER_OF_PASSENGERS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string vp_TRAILER_HAS_BREAKS {
            get {
                return ((string)(this["vp_TRAILER_HAS_BREAKS"]));
            }
            set {
                this["vp_TRAILER_HAS_BREAKS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string vp_FUEL_TYPE {
            get {
                return ((string)(this["vp_FUEL_TYPE"]));
            }
            set {
                this["vp_FUEL_TYPE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Visibility_Segments {
            get {
                return ((bool)(this["Visibility_Segments"]));
            }
            set {
                this["Visibility_Segments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int Priority_Segments {
            get {
                return ((int)(this["Priority_Segments"]));
            }
            set {
                this["Priority_Segments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("flagblue.bmp")]
        public string Icon_Segments_Standard {
            get {
                return ((string)(this["Icon_Segments_Standard"]));
            }
            set {
                this["Icon_Segments_Standard"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Nodes {
            get {
                return ((bool)(this["Nodes"]));
            }
            set {
                this["Nodes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("n_marker2.bmp")]
        public string Icon_Segments_NoStandard_NoAdd {
            get {
                return ((string)(this["Icon_Segments_NoStandard_NoAdd"]));
            }
            set {
                this["Icon_Segments_NoStandard_NoAdd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("n_marker1.bmp")]
        public string Icon_Segments_NoStandard_Add {
            get {
                return ((string)(this["Icon_Segments_NoStandard_Add"]));
            }
            set {
                this["Icon_Segments_NoStandard_Add"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1,1,1,1,1,1,1,1")]
        public string CostsDistance {
            get {
                return ((string)(this["CostsDistance"]));
            }
            set {
                this["CostsDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1,1,1,1,1,1,1,1")]
        public string CostsPeriod {
            get {
                return ((string)(this["CostsPeriod"]));
            }
            set {
                this["CostsPeriod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ROUTELISTMANOEUVRES {
            get {
                return ((bool)(this["ROUTELISTMANOEUVRES"]));
            }
            set {
                this["ROUTELISTMANOEUVRES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cbxWaypoints {
            get {
                return ((bool)(this["cbxWaypoints"]));
            }
            set {
                this["cbxWaypoints"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("location.bmp")]
        public string Icon_Matchpoint {
            get {
                return ((string)(this["Icon_Matchpoint"]));
            }
            set {
                this["Icon_Matchpoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("501")]
        public int Priority_TollSections {
            get {
                return ((int)(this["Priority_TollSections"]));
            }
            set {
                this["Priority_TollSections"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Visibility_TollSections {
            get {
                return ((bool)(this["Visibility_TollSections"]));
            }
            set {
                this["Visibility_TollSections"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("flaggreen.bmp")]
        public string Icon_TollSection_From {
            get {
                return ((string)(this["Icon_TollSection_From"]));
            }
            set {
                this["Icon_TollSection_From"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("flagred.bmp")]
        public string Icon_TollSection_To {
            get {
                return ((string)(this["Icon_TollSection_To"]));
            }
            set {
                this["Icon_TollSection_To"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GEODATASOURCE_LAYER {
            get {
                return ((string)(this["GEODATASOURCE_LAYER"]));
            }
            set {
                this["GEODATASOURCE_LAYER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DynamicInfo {
            get {
                return ((bool)(this["DynamicInfo"]));
            }
            set {
                this["DynamicInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime Tolldate {
            get {
                return ((global::System.DateTime)(this["Tolldate"]));
            }
            set {
                this["Tolldate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string vp_EMPTY_WEIGHT {
            get {
                return ((string)(this["vp_EMPTY_WEIGHT"]));
            }
            set {
                this["vp_EMPTY_WEIGHT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string vp_EMISSION_TECHNOLOGY {
            get {
                return ((string)(this["vp_EMISSION_TECHNOLOGY"]));
            }
            set {
                this["vp_EMISSION_TECHNOLOGY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string vp_LOAD_WEIGHT {
            get {
                return ((string)(this["vp_LOAD_WEIGHT"]));
            }
            set {
                this["vp_LOAD_WEIGHT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SPEED_INFOS {
            get {
                return ((string)(this["SPEED_INFOS"]));
            }
            set {
                this["SPEED_INFOS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string XMLSNIPPET {
            get {
                return ((string)(this["XMLSNIPPET"]));
            }
            set {
                this["XMLSNIPPET"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PTVBenelux")]
        public string xroute_username {
            get {
                return ((string)(this["xroute_username"]));
            }
            set {
                this["xroute_username"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PTVBenelux")]
        public string xroute_password {
            get {
                return ((string)(this["xroute_password"]));
            }
            set {
                this["xroute_password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string xmap_username {
            get {
                return ((string)(this["xmap_username"]));
            }
            set {
                this["xmap_username"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string xmap_password {
            get {
                return ((string)(this["xmap_password"]));
            }
            set {
                this["xmap_password"] = value;
            }
        }
    }
}
